import "./globals.css";
import { inter, lusitana, ubuntuMono } from "@/app/fonts";

// components
import Header from "@/components/Header";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ubuntuMono.className} antialiased`}>
        <Header />
        {children}
        </body>
    </html>
  )
}
